function createfigure(XData1, YData1, ZData1)
%CREATEFIGURE(XData1, YData1, ZData1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  ZDATA1:  line zdata

%  Auto-generated by MATLAB on 20-Mar-2024 17:56:40

% Create figure
figure1 = figure('NumberTitle','off','Name','Lorenz Attractor',...
    'Color',[0.15 0.15 0.15]);

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.07 0.1 0.74 0.95]);
hold(axes1,'on');

% Create line
line(XData1,YData1,ZData1,'Parent',axes1,'MarkerSize',25,'Marker','.',...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'Color',[1 1 0]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Parent',axes1,'Color',[0 0 1]);

% Create zlabel
zlabel('Z');

% Create ylabel
ylabel('Y');

% Create xlabel
xlabel('X');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 50]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-20 20]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-30 30]);
view(axes1,[-37.5 30]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Clipping','off','SortMethod','childorder','XTick',[],'YTick',[],...
    'ZTick',[]);
% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

